# Generated by Django 5.2.16 on 2026-07-30 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_referral_code_customer_referred_by_referral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='hashed_password',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('google', 'Google'), ('telegram', 'Telegram')], max_length=20)),
                ('provider_uid', models.CharField(help_text="The provider's own immutable id for this user.", max_length=191)),
                ('email', models.EmailField(blank=True, help_text='Address as the provider reported it, for support only.', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to='customers.customer')),
            ],
            options={
                'db_table': 'customers_socialaccount',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('provider', 'provider_uid'), name='one_link_per_provider_identity'), models.UniqueConstraint(fields=('provider', 'customer'), name='one_link_per_customer_per_provider')],
            },
        ),
    ]
