# Generated by Django 5.2.16 on 2026-07-31 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_customer_hashed_password_socialaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='avatar_updated_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='avatar_webp',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
