# Generated by Django 5.2.16 on 2026-07-31 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_customer_avatar_updated_at_customer_avatar_webp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-created_at'], 'verbose_name': 'customer', 'verbose_name_plural': 'customers'},
        ),
        migrations.AlterModelOptions(
            name='referral',
            options={'ordering': ['-created_at'], 'verbose_name': 'referral', 'verbose_name_plural': 'referrals'},
        ),
        migrations.AlterModelOptions(
            name='socialaccount',
            options={'ordering': ['-created_at'], 'verbose_name': 'social account', 'verbose_name_plural': 'social accounts'},
        ),
    ]
