# Generated by Django 5.2.16 on 2026-07-31 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_translatable_verbose_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='avatar_updated_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='avatar updated at'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='avatar_webp',
            field=models.BinaryField(blank=True, null=True, verbose_name='avatar webp'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='full_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='full name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='hashed_password',
            field=models.CharField(blank=True, max_length=255, verbose_name='hashed password'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='referral_code',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='referral code'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals_made', to='customers.customer', verbose_name='referred by'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='completed at'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referred',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_via', to='customers.customer', verbose_name='referred'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referred_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='referred email'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referrer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='customers.customer', verbose_name='referrer'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='reward_code',
            field=models.CharField(blank=True, max_length=40, verbose_name='reward code'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=10, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to='customers.customer', verbose_name='customer'),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='email',
            field=models.EmailField(blank=True, help_text='Address as the provider reported it, for support only.', max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='last_login_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login at'),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='provider',
            field=models.CharField(choices=[('google', 'Google'), ('telegram', 'Telegram')], max_length=20, verbose_name='provider'),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='provider_uid',
            field=models.CharField(help_text="The provider's own immutable id for this user.", max_length=191, verbose_name='provider uid'),
        ),
    ]
