# Generated by Django 5.2.16 on 2026-09-05 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_field_labels'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralAgent',
            fields=[
            ],
            options={
                'verbose_name': 'Agent (referal)',
                'verbose_name_plural': 'Agentlar va referallar',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('customers.customer',),
        ),
    ]
