# Generated by Django 5.2.15 on 2026-06-25 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("slug", models.SlugField(max_length=120, unique=True)),
                (
                    "iso2",
                    models.CharField(
                        help_text="ISO 3166-1 alpha-2 code, e.g. UZ", max_length=2
                    ),
                ),
                ("is_popular", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "countries",
                "db_table": "catalog_country",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, unique=True)),
                ("slug", models.SlugField(max_length=80, unique=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "db_table": "catalog_region",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("local", "Local"),
                            ("regional", "Regional"),
                            ("global", "Global"),
                        ],
                        default="local",
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                (
                    "data_amount_mb",
                    models.PositiveIntegerField(
                        default=1024, help_text="Ignored when unlimited"
                    ),
                ),
                ("is_unlimited", models.BooleanField(default=False)),
                ("validity_days", models.PositiveIntegerField(default=7)),
                ("price_usd", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "network_type",
                    models.CharField(
                        choices=[("4G", "4G / LTE"), ("5G", "5G")],
                        default="4G",
                        max_length=2,
                    ),
                ),
                ("supports_hotspot", models.BooleanField(default=True)),
                ("is_popular", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plans",
                        to="catalog.country",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plans",
                        to="catalog.region",
                    ),
                ),
            ],
            options={
                "db_table": "catalog_plan",
                "ordering": ["sort_order", "price_usd"],
            },
        ),
        migrations.AddField(
            model_name="country",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="countries",
                to="catalog.region",
            ),
        ),
    ]
