# Generated by Django 5.2.15 on 2026-07-22 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="provider",
            field=models.CharField(
                default="mock",
                help_text="Supplier key. Set to esimaccess only after package mapping is verified.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="provider_package_code",
            field=models.CharField(
                blank=True,
                help_text="Supplier package slug/code, e.g. JP_1_7 for eSIM Access.",
                max_length=120,
            ),
        ),
    ]
