# Generated by Django 5.2.16 on 2026-07-26 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_plan_provider_plan_provider_package_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='cost_usd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Supplier cost. Leave empty for plans with no supplier.', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='markup_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Overrides every pricing rule for this plan only. Leave empty to inherit.', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='price_locked',
            field=models.BooleanField(default=False, help_text='Keep the price exactly as typed; never recalculate it from cost.'),
        ),
        migrations.CreateModel(
            name='PricingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('global', 'Everything (house default)'), ('provider', 'One supplier'), ('country', 'One destination')], default='global', max_length=10)),
                ('provider', models.CharField(blank=True, help_text="Required when the scope is 'One supplier', e.g. esimaccess.", max_length=20)),
                ('markup_percent', models.DecimalField(decimal_places=2, default=30, help_text='Added on top of supplier cost.', max_digits=6)),
                ('min_margin_usd', models.DecimalField(decimal_places=2, default=0, help_text='Profit floor. A percentage on a cheap plan can be pennies; this prevents that.', max_digits=8)),
                ('rounding', models.CharField(choices=[('none', 'Exact cents'), ('charm', 'End in .99'), ('half', 'Round up to 0.50'), ('whole', 'Round up to whole dollar')], default='none', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(blank=True, help_text="Required when the scope is 'One destination'.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricing_rules', to='catalog.country')),
            ],
            options={
                'db_table': 'catalog_pricingrule',
                'ordering': ['scope', 'provider', 'country__name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('scope', 'global')), fields=('scope',), name='one_global_pricing_rule'), models.UniqueConstraint(condition=models.Q(('scope', 'provider')), fields=('provider',), name='one_rule_per_provider'), models.UniqueConstraint(condition=models.Q(('scope', 'country')), fields=('country',), name='one_rule_per_country'), models.CheckConstraint(condition=models.Q(('markup_percent__gte', 0)), name='markup_not_negative'), models.CheckConstraint(condition=models.Q(('min_margin_usd__gte', 0)), name='min_margin_not_negative')],
            },
        ),
    ]
