# Generated by Django 5.2.16 on 2026-07-28 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_plan_cost_usd_plan_markup_percent_plan_price_locked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='cost_usd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Supplier cost. Set automatically from the cheapest supplier offer, if any.', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='provider',
            field=models.CharField(default='mock', help_text='Winning supplier. Managed by the offers below when there are any.', max_length=20),
        ),
        migrations.CreateModel(
            name='SupplierOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('esimaccess', 'eSIM Access'), ('esimcard', 'eSIMCard'), ('mock', 'Mock (no real supplier)')], max_length=20)),
                ('package_code', models.CharField(help_text="This supplier's own code for the package, e.g. TR_5_30.", max_length=120)),
                ('cost_usd', models.DecimalField(decimal_places=2, help_text='Wholesale price this supplier charges us.', max_digits=8)),
                ('is_available', models.BooleanField(default=True, help_text='Uncheck to take a supplier out of the running without losing its price.')),
                ('unavailable_reason', models.CharField(blank=True, help_text="Why it is out — e.g. 'out of stock', 'no balance'.", max_length=200)),
                ('last_synced_at', models.DateTimeField(blank=True, help_text='When a price sync last confirmed this offer.', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='catalog.plan')),
            ],
            options={
                'db_table': 'catalog_supplieroffer',
                'ordering': ['cost_usd'],
                'constraints': [models.UniqueConstraint(fields=('plan', 'provider'), name='one_offer_per_plan_per_provider'), models.CheckConstraint(condition=models.Q(('cost_usd__gte', 0)), name='offer_cost_not_negative')],
            },
        ),
    ]
