# Generated by Django 5.2.16 on 2026-07-29 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_plan_cost_usd_alter_plan_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='price_note',
            field=models.CharField(blank=True, help_text="Optional text shown beside the price, e.g. '+ deposit'. The number itself stays in the price field.", max_length=120),
        ),
        migrations.AlterField(
            model_name='plan',
            name='cost_usd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Supplier cost. Set automatically from the cheapest supplier offer, if any.', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='price_usd',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='supplieroffer',
            name='cost_usd',
            field=models.DecimalField(decimal_places=2, help_text='Wholesale price this supplier charges us.', max_digits=12),
        ),
    ]
