# Generated by Django 5.2.16 on 2026-07-31 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_plan_price_note_alter_plan_cost_usd_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': 'country', 'verbose_name_plural': 'countries'},
        ),
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['sort_order', 'price_usd'], 'verbose_name': 'plan', 'verbose_name_plural': 'plans'},
        ),
        migrations.AlterModelOptions(
            name='pricingrule',
            options={'ordering': ['scope', 'provider', 'country__name'], 'verbose_name': 'pricing rule', 'verbose_name_plural': 'pricing rules'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': 'region', 'verbose_name_plural': 'regions'},
        ),
        migrations.AlterModelOptions(
            name='supplieroffer',
            options={'ordering': ['cost_usd'], 'verbose_name': 'supplier offer', 'verbose_name_plural': 'supplier offers'},
        ),
    ]
