# Generated by Django 5.2.16 on 2026-07-31 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_translatable_verbose_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='country',
            name='is_popular',
            field=models.BooleanField(default=False, verbose_name='is popular'),
        ),
        migrations.AlterField(
            model_name='country',
            name='iso2',
            field=models.CharField(help_text='ISO 3166-1 alpha-2 code, e.g. UZ', max_length=2, verbose_name='iso2'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=120, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='country',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='countries', to='catalog.region', verbose_name='region'),
        ),
        migrations.AlterField(
            model_name='country',
            name='slug',
            field=models.SlugField(max_length=120, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='country',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='sort order'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='cost_usd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Supplier cost. Set automatically from the cheapest supplier offer, if any.', max_digits=12, null=True, verbose_name='cost usd'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='catalog.country', verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='data_amount_mb',
            field=models.PositiveIntegerField(default=1024, help_text='Ignored when unlimited', verbose_name='data amount mb'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='is_popular',
            field=models.BooleanField(default=False, verbose_name='is popular'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='is_unlimited',
            field=models.BooleanField(default=False, verbose_name='is unlimited'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='markup_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Overrides every pricing rule for this plan only. Leave empty to inherit.', max_digits=6, null=True, verbose_name='markup percent'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='network_type',
            field=models.CharField(choices=[('4G', '4G / LTE'), ('5G', '5G')], default='4G', max_length=2, verbose_name='network type'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='price_locked',
            field=models.BooleanField(default=False, help_text='Keep the price exactly as typed; never recalculate it from cost.', verbose_name='price locked'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='price_note',
            field=models.CharField(blank=True, help_text="Optional text shown beside the price, e.g. '+ deposit'. The number itself stays in the price field.", max_length=120, verbose_name='price note'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='price_usd',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='price usd'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='provider',
            field=models.CharField(default='mock', help_text='Winning supplier. Managed by the offers below when there are any.', max_length=20, verbose_name='provider'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='provider_package_code',
            field=models.CharField(blank=True, help_text='Supplier package slug/code, e.g. JP_1_7 for eSIM Access.', max_length=120, verbose_name='provider package code'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='catalog.region', verbose_name='region'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='scope',
            field=models.CharField(choices=[('local', 'Local'), ('regional', 'Regional'), ('global', 'Global')], default='local', max_length=10, verbose_name='scope'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='sort order'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='supports_hotspot',
            field=models.BooleanField(default=True, verbose_name='supports hotspot'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='title',
            field=models.CharField(max_length=120, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='validity_days',
            field=models.PositiveIntegerField(default=7, verbose_name='validity days'),
        ),
        migrations.AlterField(
            model_name='pricingrule',
            name='country',
            field=models.ForeignKey(blank=True, help_text="Required when the scope is 'One destination'.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricing_rules', to='catalog.country', verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='pricingrule',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='pricingrule',
            name='markup_percent',
            field=models.DecimalField(decimal_places=2, default=30, help_text='Added on top of supplier cost.', max_digits=6, verbose_name='markup percent'),
        ),
        migrations.AlterField(
            model_name='pricingrule',
            name='min_margin_usd',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Profit floor. A percentage on a cheap plan can be pennies; this prevents that.', max_digits=8, verbose_name='min margin usd'),
        ),
        migrations.AlterField(
            model_name='pricingrule',
            name='note',
            field=models.CharField(blank=True, max_length=200, verbose_name='note'),
        ),
        migrations.AlterField(
            model_name='pricingrule',
            name='provider',
            field=models.CharField(blank=True, help_text="Required when the scope is 'One supplier', e.g. esimaccess.", max_length=20, verbose_name='provider'),
        ),
        migrations.AlterField(
            model_name='pricingrule',
            name='rounding',
            field=models.CharField(choices=[('none', 'Exact cents'), ('charm', 'End in .99'), ('half', 'Round up to 0.50'), ('whole', 'Round up to whole dollar')], default='none', max_length=10, verbose_name='rounding'),
        ),
        migrations.AlterField(
            model_name='pricingrule',
            name='scope',
            field=models.CharField(choices=[('global', 'Everything (house default)'), ('provider', 'One supplier'), ('country', 'One destination')], default='global', max_length=10, verbose_name='scope'),
        ),
        migrations.AlterField(
            model_name='pricingrule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=80, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='region',
            name='slug',
            field=models.SlugField(max_length=80, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='region',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='sort order'),
        ),
        migrations.AlterField(
            model_name='supplieroffer',
            name='cost_usd',
            field=models.DecimalField(decimal_places=2, help_text='Wholesale price this supplier charges us.', max_digits=12, verbose_name='cost usd'),
        ),
        migrations.AlterField(
            model_name='supplieroffer',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Uncheck to take a supplier out of the running without losing its price.', verbose_name='is available'),
        ),
        migrations.AlterField(
            model_name='supplieroffer',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, help_text='When a price sync last confirmed this offer.', null=True, verbose_name='last synced at'),
        ),
        migrations.AlterField(
            model_name='supplieroffer',
            name='package_code',
            field=models.CharField(help_text="This supplier's own code for the package, e.g. TR_5_30.", max_length=120, verbose_name='package code'),
        ),
        migrations.AlterField(
            model_name='supplieroffer',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='catalog.plan', verbose_name='plan'),
        ),
        migrations.AlterField(
            model_name='supplieroffer',
            name='provider',
            field=models.CharField(choices=[('esimaccess', 'eSIM Access'), ('esimcard', 'eSIMCard'), ('mock', 'Mock (no real supplier)')], max_length=20, verbose_name='provider'),
        ),
        migrations.AlterField(
            model_name='supplieroffer',
            name='unavailable_reason',
            field=models.CharField(blank=True, help_text="Why it is out — e.g. 'out of stock', 'no balance'.", max_length=200, verbose_name='unavailable reason'),
        ),
        migrations.AlterField(
            model_name='supplieroffer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
    ]
