# Generated by Django 5.2.16 on 2026-07-31 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_field_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='name_ru',
            field=models.CharField(blank=True, help_text='Russian name. Leave blank to show the English one.', max_length=120, verbose_name='name ru'),
        ),
        migrations.AddField(
            model_name='country',
            name='name_uz',
            field=models.CharField(blank=True, help_text='Uzbek name. Leave blank to show the English one.', max_length=120, verbose_name='name uz'),
        ),
        migrations.AddField(
            model_name='region',
            name='name_ru',
            field=models.CharField(blank=True, help_text='Russian name. Leave blank to show the English one.', max_length=80, verbose_name='name ru'),
        ),
        migrations.AddField(
            model_name='region',
            name='name_uz',
            field=models.CharField(blank=True, help_text='Uzbek name. Leave blank to show the English one.', max_length=80, verbose_name='name uz'),
        ),
    ]
