# Generated by Django 5.2.16 on 2026-08-02 22:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_country_name_ru_country_name_uz_region_name_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='markup_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Overrides every pricing rule for this plan only. Leave empty to inherit.', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='markup percent'),
        ),
    ]
