# Generated by Django 5.2.17 on 2026-08-05 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_plan_markup_percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogSyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(help_text="Which wholesaler, or 'all' when both were synced.", max_length=40, verbose_name='provider')),
                ('dry_run', models.BooleanField(default=True, help_text='A preview writes nothing.', verbose_name='preview only')),
                ('status', models.CharField(choices=[('running', 'Running'), ('ok', 'Finished'), ('failed', 'Failed')], default='running', max_length=10, verbose_name='status')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='started at')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='finished at')),
                ('packages_read', models.PositiveIntegerField(default=0, verbose_name='packages read')),
                ('countries_created', models.PositiveIntegerField(default=0, verbose_name='destinations added')),
                ('plans_created', models.PositiveIntegerField(default=0, verbose_name='plans added')),
                ('offers_written', models.PositiveIntegerField(default=0, verbose_name='prices written')),
                ('log', models.TextField(blank=True, verbose_name='log')),
            ],
            options={
                'verbose_name': 'catalogue sync',
                'verbose_name_plural': 'catalogue syncs',
                'db_table': 'catalog_catalogsyncrun',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AlterField(
            model_name='supplieroffer',
            name='provider',
            field=models.CharField(choices=[('esimaccess', 'eSIM Access'), ('esimcard', 'eSIMCard'), ('mock', 'No supplier — cannot be sold')], max_length=20, verbose_name='provider'),
        ),
    ]
