# Generated by Django 5.2.17 on 2026-08-06 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_catalogsyncrun_alter_supplieroffer_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingrule',
            name='tier_data_mb',
            field=models.PositiveIntegerField(blank=True, help_text='Traffic size in MB, e.g. 1024 for 1 GB. Leave empty for any size.', null=True, verbose_name='traffic size (MB)'),
        ),
        migrations.AddField(
            model_name='pricingrule',
            name='tier_days',
            field=models.PositiveIntegerField(blank=True, help_text='Validity in days. Leave empty to match any duration of that size.', null=True, verbose_name='validity (days)'),
        ),
        migrations.AlterField(
            model_name='pricingrule',
            name='scope',
            field=models.CharField(choices=[('global', 'Everything (house default)'), ('provider', 'One supplier'), ('country', 'One destination'), ('tier', 'One traffic size, every destination')], default='global', max_length=10, verbose_name='scope'),
        ),
    ]
