# Generated by Django 5.2.17 on 2026-08-06 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_pricingrule_tier_data_mb_pricingrule_tier_days_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pricingrule',
            name='one_rule_per_country',
        ),
        migrations.AddConstraint(
            model_name='pricingrule',
            constraint=models.UniqueConstraint(condition=models.Q(('scope', 'country'), ('tier_data_mb__isnull', True)), fields=('country',), name='one_rule_per_country'),
        ),
        migrations.AddConstraint(
            model_name='pricingrule',
            constraint=models.UniqueConstraint(condition=models.Q(('scope', 'country'), ('tier_data_mb__isnull', False)), fields=('country', 'tier_data_mb', 'tier_days'), name='one_rule_per_country_tier'),
        ),
        migrations.AddConstraint(
            model_name='pricingrule',
            constraint=models.UniqueConstraint(condition=models.Q(('scope', 'tier'), ('tier_days__isnull', False)), fields=('tier_data_mb', 'tier_days'), name='one_rule_per_tier'),
        ),
        migrations.AddConstraint(
            model_name='pricingrule',
            constraint=models.UniqueConstraint(condition=models.Q(('scope', 'tier'), ('tier_days__isnull', True)), fields=('tier_data_mb',), name='one_rule_per_tier_any_duration'),
        ),
    ]
