# Generated by Django 5.2.16 on 2026-08-16 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_remove_pricingrule_one_rule_per_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='coverage_iso2',
            field=models.TextField(blank=True, default='', help_text='ISO2 codes this multi-country plan covers, comma separated.', verbose_name='coverage'),
        ),
    ]
