# Generated by Django 5.2.16 on 2026-08-17 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_plan_coverage_iso2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='scope',
            field=models.CharField(choices=[('local', 'Local'), ('regional', 'Regional'), ('global', 'Global'), ('topup', 'Top-up')], default='local', max_length=10, verbose_name='scope'),
        ),
    ]
