# Generated by Django 5.2.16 on 2026-08-22 10:47

import django.db.models.deletion
from django.db import migrations, models


def seed_the_current_ladder(apps, schema_editor):
    """The seven rungs the catalogue already sold, moved out of code into rows.

    Written as a data migration rather than left to the fallback so the table is
    the source of truth from the first deploy — and so the owner can see, edit
    and reorder what was previously a Python list they had no access to.
    """
    SellableShape = apps.get_model("catalog", "SellableShape")
    rungs = [
        (1024, 7, "4G", "Bir haftalik eng arzon kirish nuqtasi — 204 davlatda bor"),
        (3072, 15, "5G", "Qisqa safar"),
        (3072, 30, "5G", "Oylik, kam sarflaydiganlar uchun"),
        (5120, 30, "5G", "Eng ko'p sotiladigan oylik"),
        (10240, 30, "5G", "Ko'p sarflaydiganlar"),
        (20480, 30, "5G", "Uzoq safar"),
        (51200, 30, "5G", "Eng yuqori pog'ona — 40 davlatda bor"),
    ]
    for order, (mb, days, network, note) in enumerate(rungs):
        SellableShape.objects.update_or_create(
            data_mb=mb,
            days=days,
            country=None,
            defaults={"network": network, "sort_order": order, "is_active": True, "note": note},
        )


def forget_the_ladder(apps, schema_editor):
    apps.get_model("catalog", "SellableShape").objects.filter(country__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_topup_support'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellableShape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_mb', models.PositiveIntegerField(help_text="1024 = 1 GB. Must match the wholesaler's shape exactly.", verbose_name='traffic (MB)')),
                ('days', models.PositiveIntegerField(verbose_name='days')),
                ('network', models.CharField(choices=[('4G', '4G'), ('5G', '5G')], default='5G', max_length=2, verbose_name='network shown')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Lowest first. This is the order the customer reads.', verbose_name='order on the page')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('note', models.CharField(blank=True, help_text='Why this rung exists. Read by whoever wonders later.', max_length=200, verbose_name='note')),
                ('country', models.ForeignKey(blank=True, help_text='Leave empty to offer this shape everywhere it exists.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sellable_shapes', to='catalog.country', verbose_name='only this destination')),
            ],
            options={
                'verbose_name': 'sellable shape',
                'verbose_name_plural': 'sellable shapes',
                'ordering': ('sort_order', 'data_mb', 'days'),
                'constraints': [models.UniqueConstraint(fields=('data_mb', 'days', 'country'), name='one_rung_per_shape_and_country')],
            },
        ),
        migrations.RunPython(seed_the_current_ladder, forget_the_ladder),
    ]
