# Generated by Django 5.2.15 on 2026-06-29 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Benefit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="Globe2",
                        help_text="Lucide icon name, e.g. Globe2, Radio, Zap, Wallet, ShieldCheck.",
                        max_length=40,
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="English (base).", max_length=120),
                ),
                ("text", models.TextField(help_text="English (base).")),
                ("title_ru", models.CharField(blank=True, max_length=120)),
                ("text_ru", models.TextField(blank=True)),
                ("title_uz", models.CharField(blank=True, max_length=120)),
                ("text_uz", models.TextField(blank=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "content_benefit",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "content_device",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="PromoBanner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "eyebrow",
                    models.CharField(help_text="English (base).", max_length=80),
                ),
                (
                    "title",
                    models.CharField(help_text="English (base).", max_length=160),
                ),
                (
                    "text",
                    models.TextField(
                        help_text="English (base). Use {{code}} where the code should appear."
                    ),
                ),
                ("eyebrow_ru", models.CharField(blank=True, max_length=80)),
                ("title_ru", models.CharField(blank=True, max_length=160)),
                ("text_ru", models.TextField(blank=True)),
                ("eyebrow_uz", models.CharField(blank=True, max_length=80)),
                ("title_uz", models.CharField(blank=True, max_length=160)),
                ("text_uz", models.TextField(blank=True)),
                ("code", models.CharField(default="WELCOME10", max_length=40)),
                ("cta_link", models.CharField(default="/destinations", max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Promo banner",
                "db_table": "content_promobanner",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                (
                    "location",
                    models.CharField(
                        help_text="English (base), e.g. 'Tashkent → Tokyo'.",
                        max_length=120,
                    ),
                ),
                ("text", models.TextField(help_text="English (base).")),
                ("location_ru", models.CharField(blank=True, max_length=120)),
                ("text_ru", models.TextField(blank=True)),
                ("location_uz", models.CharField(blank=True, max_length=120)),
                ("text_uz", models.TextField(blank=True)),
                ("rating", models.PositiveSmallIntegerField(default=5)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "content_testimonial",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.AddField(
            model_name="faq",
            name="answer_ru",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="faq",
            name="answer_uz",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="faq",
            name="question_ru",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="faq",
            name="question_uz",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
