# Generated by Django 5.2.16 on 2026-07-31 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_testimonial_moderation'),
        ('orders', '0004_order_amount_uzs_order_exchange_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promobanner',
            name='promo_code',
            field=models.ForeignKey(blank=True, help_text='Link the promo code this banner advertises. Its discount — percent or fixed amount — is what the site shows, so there is one number to change, not two.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banners', to='orders.promocode'),
        ),
        migrations.AddField(
            model_name='promobanner',
            name='strip_text',
            field=models.CharField(blank=True, help_text="Short bar text, English. e.g. '20$ chegirma'", max_length=60),
        ),
        migrations.AddField(
            model_name='promobanner',
            name='strip_text_ru',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='promobanner',
            name='strip_text_uz',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
