# Generated by Django 5.2.16 on 2026-07-31 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_promobanner_promo_code_promobanner_strip_text_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': 'banner', 'verbose_name_plural': 'banners'},
        ),
        migrations.AlterModelOptions(
            name='benefit',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': 'benefit', 'verbose_name_plural': 'benefits'},
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': 'device', 'verbose_name_plural': 'devices'},
        ),
        migrations.AlterModelOptions(
            name='promobanner',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Promo banner', 'verbose_name_plural': 'Promo banners'},
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': 'testimonial', 'verbose_name_plural': 'testimonials'},
        ),
    ]
