# Generated by Django 5.2.16 on 2026-07-31 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_translatable_verbose_names'),
        ('customers', '0006_field_labels'),
        ('orders', '0007_field_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='cta_link',
            field=models.CharField(blank=True, max_length=255, verbose_name='cta link'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='cta_text',
            field=models.CharField(blank=True, max_length=60, verbose_name='cta text'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image_url',
            field=models.URLField(blank=True, verbose_name='image url'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='sort order'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, verbose_name='subtitle'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(max_length=120, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='benefit',
            name='icon',
            field=models.CharField(default='Globe2', help_text='Lucide icon name, e.g. Globe2, Radio, Zap, Wallet, ShieldCheck.', max_length=40, verbose_name='icon'),
        ),
        migrations.AlterField(
            model_name='benefit',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='benefit',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='sort order'),
        ),
        migrations.AlterField(
            model_name='benefit',
            name='text',
            field=models.TextField(help_text='English (base).', verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='benefit',
            name='text_ru',
            field=models.TextField(blank=True, verbose_name='text ru'),
        ),
        migrations.AlterField(
            model_name='benefit',
            name='text_uz',
            field=models.TextField(blank=True, verbose_name='text uz'),
        ),
        migrations.AlterField(
            model_name='benefit',
            name='title',
            field=models.CharField(help_text='English (base).', max_length=120, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='benefit',
            name='title_ru',
            field=models.CharField(blank=True, max_length=120, verbose_name='title ru'),
        ),
        migrations.AlterField(
            model_name='benefit',
            name='title_uz',
            field=models.CharField(blank=True, max_length=120, verbose_name='title uz'),
        ),
        migrations.AlterField(
            model_name='device',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(max_length=120, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='device',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='sort order'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(verbose_name='answer'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer_ru',
            field=models.TextField(blank=True, verbose_name='answer ru'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer_uz',
            field=models.TextField(blank=True, verbose_name='answer uz'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('setup', 'Setup & activation'), ('billing', 'Billing & payments'), ('device', 'Device compatibility')], default='general', max_length=20, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.CharField(max_length=255, verbose_name='question'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question_ru',
            field=models.CharField(blank=True, max_length=255, verbose_name='question ru'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question_uz',
            field=models.CharField(blank=True, max_length=255, verbose_name='question uz'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='sort order'),
        ),
        migrations.AlterField(
            model_name='promobanner',
            name='code',
            field=models.CharField(default='WELCOME10', max_length=40, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='promobanner',
            name='cta_link',
            field=models.CharField(default='/destinations', max_length=255, verbose_name='cta link'),
        ),
        migrations.AlterField(
            model_name='promobanner',
            name='eyebrow',
            field=models.CharField(help_text='English (base).', max_length=80, verbose_name='eyebrow'),
        ),
        migrations.AlterField(
            model_name='promobanner',
            name='eyebrow_ru',
            field=models.CharField(blank=True, max_length=80, verbose_name='eyebrow ru'),
        ),
        migrations.AlterField(
            model_name='promobanner',
            name='eyebrow_uz',
            field=models.CharField(blank=True, max_length=80, verbose_name='eyebrow uz'),
        ),
        migrations.AlterField(
            model_name='promobanner',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='promobanner',
            name='promo_code',
            field=models.ForeignKey(blank=True, help_text='Link the promo code this banner advertises. Its discount — percent or fixed amount — is what the site shows, so there is one number to change, not two.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banners', to='orders.promocode', verbose_name='promo code'),
        ),
        migrations.AlterField(
            model_name='promobanner',
            name='strip_text',
            field=models.CharField(blank=True, help_text="Short bar text, English. e.g. '20$ chegirma'", max_length=60, verbose_name='strip text'),
        ),
        migrations.AlterField(
            model_name='promobanner',
            name='strip_text_ru',
            field=models.CharField(blank=True, max_length=60, verbose_name='strip text ru'),
        ),
        migrations.AlterField(
            model_name='promobanner',
            name='strip_text_uz',
            field=models.CharField(blank=True, max_length=60, verbose_name='strip text uz'),
        ),
        migrations.AlterField(
            model_name='promobanner',
            name='text',
            field=models.TextField(help_text='English (base). Use {{code}} where the code should appear.', verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='promobanner',
            name='text_ru',
            field=models.TextField(blank=True, verbose_name='text ru'),
        ),
        migrations.AlterField(
            model_name='promobanner',
            name='text_uz',
            field=models.TextField(blank=True, verbose_name='text uz'),
        ),
        migrations.AlterField(
            model_name='promobanner',
            name='title',
            field=models.CharField(help_text='English (base).', max_length=160, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='promobanner',
            name='title_ru',
            field=models.CharField(blank=True, max_length=160, verbose_name='title ru'),
        ),
        migrations.AlterField(
            model_name='promobanner',
            name='title_uz',
            field=models.CharField(blank=True, max_length=160, verbose_name='title uz'),
        ),
        migrations.AlterField(
            model_name='promobanner',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='customer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonial', to='customers.customer', verbose_name='customer'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='location',
            field=models.CharField(help_text="English (base), e.g. 'Tashkent → Tokyo'.", max_length=120, verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='location_ru',
            field=models.CharField(blank=True, max_length=120, verbose_name='location ru'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='location_uz',
            field=models.CharField(blank=True, max_length=120, verbose_name='location uz'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='moderation_status',
            field=models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10, verbose_name='moderation status'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='name',
            field=models.CharField(max_length=80, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='rating',
            field=models.PositiveSmallIntegerField(default=5, verbose_name='rating'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='sort order'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='text',
            field=models.TextField(help_text='English (base).', verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='text_ru',
            field=models.TextField(blank=True, verbose_name='text ru'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='text_uz',
            field=models.TextField(blank=True, verbose_name='text uz'),
        ),
    ]
