# Generated by Django 5.2.15 on 2026-07-22 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="esim",
            name="provider",
            field=models.CharField(default="mock", max_length=20),
        ),
        migrations.AddField(
            model_name="esim",
            name="provider_esim_tran_no",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name="esim",
            name="provider_qr_url",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="esim",
            name="provider_status",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="order",
            name="provider",
            field=models.CharField(default="mock", max_length=20),
        ),
        migrations.AddField(
            model_name="order",
            name="provider_order_no",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name="order",
            name="provider_status",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="order",
            name="provider_transaction_id",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
