# Generated by Django 5.2.16 on 2026-07-26 16:54

import catalog.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_esim_provider_esim_provider_esim_tran_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esim',
            name='qr_image',
            field=catalog.fields.EncryptedTextField(blank=True, help_text='Base64 PNG data URL (encrypted at rest)'),
        ),
        migrations.AlterField(
            model_name='esim',
            name='qr_payload',
            field=catalog.fields.EncryptedCharField(max_length=255),
        ),
    ]
