# Generated by Django 5.2.16 on 2026-07-26 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_esim_qr_image_alter_esim_qr_payload'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount_uzs',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Som amount frozen at checkout. Payme is validated against this.', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='USD→UZS rate used to freeze amount_uzs.', max_digits=12, null=True),
        ),
        migrations.CreateModel(
            name='PaymeTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('amount_tiyin', models.BigIntegerField()),
                ('account', models.CharField(help_text='The account value Payme sent.', max_length=64)),
                ('state', models.IntegerField(choices=[(1, 'Created'), (2, 'Performed'), (-1, 'Cancelled'), (-2, 'Refunded')], default=1)),
                ('reason', models.IntegerField(blank=True, help_text='Payme cancellation reason.', null=True)),
                ('create_time', models.BigIntegerField(default=0)),
                ('perform_time', models.BigIntegerField(default=0)),
                ('cancel_time', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payme_transactions', to='orders.order')),
            ],
            options={
                'db_table': 'orders_paymetransaction',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['state', '-created_at'], name='orders_paym_state_f0b77a_idx'), models.Index(fields=['create_time'], name='orders_paym_create__d2c720_idx')],
            },
        ),
    ]
