# Generated by Django 5.2.16 on 2026-07-31 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_amount_uzs_order_exchange_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='min_order_usd',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Smallest order this code applies to. Leave at 0 for no minimum — but a fixed-amount discount larger than your cheapest plan makes that plan free.', max_digits=8),
        ),
    ]
