# Generated by Django 5.2.16 on 2026-07-31 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_promocode_min_order_usd'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'order', 'verbose_name_plural': 'orders'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'order item', 'verbose_name_plural': 'order items'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at'], 'verbose_name': 'payment', 'verbose_name_plural': 'payments'},
        ),
        migrations.AlterModelOptions(
            name='paymetransaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'Payme transaction', 'verbose_name_plural': 'Payme transactions'},
        ),
        migrations.AlterModelOptions(
            name='promocode',
            options={'ordering': ['-created_at'], 'verbose_name': 'promo code', 'verbose_name_plural': 'promo codes'},
        ),
    ]
