# Generated by Django 5.2.16 on 2026-07-31 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_field_labels'),
        ('customers', '0006_field_labels'),
        ('orders', '0006_translatable_verbose_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esim',
            name='activated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='activated at'),
        ),
        migrations.AlterField(
            model_name='esim',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='esim',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='esims', to='customers.customer', verbose_name='customer'),
        ),
        migrations.AlterField(
            model_name='esim',
            name='data_total_mb',
            field=models.PositiveIntegerField(default=0, verbose_name='data total mb'),
        ),
        migrations.AlterField(
            model_name='esim',
            name='data_used_mb',
            field=models.PositiveIntegerField(default=0, verbose_name='data used mb'),
        ),
        migrations.AlterField(
            model_name='esim',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='expires at'),
        ),
        migrations.AlterField(
            model_name='esim',
            name='iccid',
            field=models.CharField(max_length=22, unique=True, verbose_name='iccid'),
        ),
        migrations.AlterField(
            model_name='esim',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='esims', to='orders.order', verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='esim',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='esims', to='catalog.plan', verbose_name='plan'),
        ),
        migrations.AlterField(
            model_name='esim',
            name='provider',
            field=models.CharField(default='mock', max_length=20, verbose_name='provider'),
        ),
        migrations.AlterField(
            model_name='esim',
            name='provider_esim_tran_no',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='provider esim tran no'),
        ),
        migrations.AlterField(
            model_name='esim',
            name='provider_qr_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='provider qr url'),
        ),
        migrations.AlterField(
            model_name='esim',
            name='provider_status',
            field=models.CharField(blank=True, max_length=40, verbose_name='provider status'),
        ),
        migrations.AlterField(
            model_name='esim',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('expired', 'Expired')], default='pending', max_length=10, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='esim',
            name='validity_days',
            field=models.PositiveIntegerField(default=7, verbose_name='validity days'),
        ),
        migrations.AlterField(
            model_name='order',
            name='amount_uzs',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Som amount frozen at checkout. Payme is validated against this.', max_digits=14, null=True, verbose_name='amount uzs'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='customers.customer', verbose_name='customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='discount'),
        ),
        migrations.AlterField(
            model_name='order',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='USD→UZS rate used to freeze amount_uzs.', max_digits=12, null=True, verbose_name='exchange rate'),
        ),
        migrations.AlterField(
            model_name='order',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='paid at'),
        ),
        migrations.AlterField(
            model_name='order',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.promocode', verbose_name='promo code'),
        ),
        migrations.AlterField(
            model_name='order',
            name='provider',
            field=models.CharField(default='mock', max_length=20, verbose_name='provider'),
        ),
        migrations.AlterField(
            model_name='order',
            name='provider_order_no',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='provider order no'),
        ),
        migrations.AlterField(
            model_name='order',
            name='provider_status',
            field=models.CharField(blank=True, max_length=40, verbose_name='provider status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='provider_transaction_id',
            field=models.CharField(blank=True, max_length=64, verbose_name='provider transaction id'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=12, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='subtotal'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='total'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='catalog.plan', verbose_name='plan'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='quantity'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='unit price'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(default='mock', max_length=30, verbose_name='method'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order', verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='provider_ref',
            field=models.CharField(blank=True, max_length=64, verbose_name='provider ref'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='success', max_length=10, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='paymetransaction',
            name='account',
            field=models.CharField(help_text='The account value Payme sent.', max_length=64, verbose_name='account'),
        ),
        migrations.AlterField(
            model_name='paymetransaction',
            name='amount_tiyin',
            field=models.BigIntegerField(verbose_name='amount tiyin'),
        ),
        migrations.AlterField(
            model_name='paymetransaction',
            name='cancel_time',
            field=models.BigIntegerField(default=0, verbose_name='cancel time'),
        ),
        migrations.AlterField(
            model_name='paymetransaction',
            name='create_time',
            field=models.BigIntegerField(default=0, verbose_name='create time'),
        ),
        migrations.AlterField(
            model_name='paymetransaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='paymetransaction',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payme_transactions', to='orders.order', verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='paymetransaction',
            name='perform_time',
            field=models.BigIntegerField(default=0, verbose_name='perform time'),
        ),
        migrations.AlterField(
            model_name='paymetransaction',
            name='reason',
            field=models.IntegerField(blank=True, help_text='Payme cancellation reason.', null=True, verbose_name='reason'),
        ),
        migrations.AlterField(
            model_name='paymetransaction',
            name='state',
            field=models.IntegerField(choices=[(1, 'Created'), (2, 'Performed'), (-1, 'Cancelled'), (-2, 'Refunded')], default=1, verbose_name='state'),
        ),
        migrations.AlterField(
            model_name='paymetransaction',
            name='transaction_id',
            field=models.CharField(db_index=True, max_length=64, unique=True, verbose_name='transaction id'),
        ),
        migrations.AlterField(
            model_name='paymetransaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='code',
            field=models.CharField(max_length=40, unique=True, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='discount_type',
            field=models.CharField(choices=[('percent', 'Percent'), ('fixed', 'Fixed amount')], default='percent', max_length=10, verbose_name='discount type'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='discount value'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='max_uses',
            field=models.PositiveIntegerField(default=0, help_text='0 = unlimited', verbose_name='max uses'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='min_order_usd',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Smallest order this code applies to. Leave at 0 for no minimum — but a fixed-amount discount larger than your cheapest plan makes that plan free.', max_digits=8, verbose_name='min order usd'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='used_count',
            field=models.PositiveIntegerField(default=0, verbose_name='used count'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='valid_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='valid until'),
        ),
    ]
