# Generated by Django 5.2.16 on 2026-08-03 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_field_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Supplier cost per unit at the time of sale.', max_digits=12, null=True, verbose_name='unit cost'),
        ),
    ]
