# Generated by Django 5.2.16 on 2026-08-04 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_orderitem_unit_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtmosTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=64, unique=True, verbose_name='transaction id')),
                ('amount_tiyin', models.BigIntegerField(verbose_name='amount tiyin')),
                ('account', models.CharField(help_text='The account value ATMOS sent.', max_length=64, verbose_name='account')),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('rejected', 'Rejected')], max_length=16, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atmos_transactions', to='orders.order', verbose_name='order')),
            ],
            options={
                'verbose_name': 'ATMOS transaction',
                'verbose_name_plural': 'ATMOS transactions',
                'db_table': 'orders_atmostransaction',
                'ordering': ['-created_at'],
            },
        ),
    ]
