# Generated by Django 5.2.17 on 2026-08-05 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_atmostransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=20, verbose_name='provider')),
                ('line_key', models.CharField(help_text='Which unit of the order this row bought.', max_length=40, verbose_name='line key')),
                ('package_code', models.CharField(blank=True, max_length=120, verbose_name='package code')),
                ('state', models.CharField(choices=[('claimed', 'Claimed — outcome unknown'), ('done', 'Bought'), ('failed', 'Refused before charge')], default='claimed', max_length=10, verbose_name='state')),
                ('supplier_ref', models.CharField(blank=True, max_length=120, verbose_name='supplier reference')),
                ('iccid', models.CharField(blank=True, max_length=32, verbose_name='ICCID')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='note')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_purchases', to='orders.order', verbose_name='order')),
            ],
            options={
                'verbose_name': 'supplier purchase',
                'verbose_name_plural': 'supplier purchases',
                'db_table': 'orders_supplierpurchase',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('order', 'provider', 'line_key'), name='uniq_supplier_purchase_per_unit')],
            },
        ),
    ]
