# Generated by Django 5.2.17 on 2026-08-06 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_field_labels'),
        ('orders', '0010_supplierpurchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='issued_to',
            field=models.ForeignKey(blank=True, help_text="When set, only this customer can redeem the code. Cashback is earned by a person, so leaving it open would let a code posted in a group chat discount everyone's order.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promo_codes', to='customers.customer', verbose_name='issued to'),
        ),
        migrations.AddField(
            model_name='promocode',
            name='reason',
            field=models.CharField(choices=[('manual', 'Created by staff'), ('referral', 'Referral cashback'), ('loyalty', 'Repeat-purchase cashback')], default='manual', help_text='Why this code exists. Cashback codes are issued automatically.', max_length=10, verbose_name='reason'),
        ),
    ]
