# Generated by Django 5.2.16 on 2026-08-10 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_promocode_issued_to_promocode_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='first_order_only',
            field=models.BooleanField(default=False, help_text='Redeemable only by a customer who has never paid for an order. WELCOME10 is advertised as a discount on your first eSIM, and without this it applied to every later one as well — the same customer kept getting 10% off forever.', verbose_name='first order only'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='reason',
            field=models.CharField(blank=True, choices=[('manual', 'Created by staff'), ('referral', 'Referral cashback'), ('loyalty', 'Repeat-purchase cashback')], default='manual', help_text='Why this code exists. Left alone for codes staff create; the worker sets it for the two cashback schemes.', max_length=10, verbose_name='reason'),
        ),
    ]
