# Generated by Django 5.2.16 on 2026-08-10 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_remove_pricingrule_one_rule_per_country_and_more'),
        ('customers', '0006_field_labels'),
        ('orders', '0012_promocode_first_order_only'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_complimentary',
            field=models.BooleanField(default=False, help_text='Issued by staff at cost, with no payment taken.', verbose_name='is complimentary'),
        ),
        migrations.CreateModel(
            name='ComplimentaryGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(help_text='Why this was given away. Required — a giveaway with no reason is indistinguishable from a mistake.', max_length=200, verbose_name='reason')),
                ('cost_usd', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='cost usd')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('customer', models.ForeignKey(help_text='Who receives the eSIM. They must already have an account.', on_delete=django.db.models.deletion.CASCADE, related_name='complimentary_grants', to='customers.customer', verbose_name='customer')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complimentary_grants', to=settings.AUTH_USER_MODEL, verbose_name='granted by')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complimentary_grants', to='orders.order', verbose_name='order')),
                ('plan', models.ForeignKey(help_text='Which tariff to buy for them.', on_delete=django.db.models.deletion.PROTECT, related_name='complimentary_grants', to='catalog.plan', verbose_name='plan')),
            ],
            options={
                'verbose_name': 'complimentary grant',
                'verbose_name_plural': 'complimentary grants',
                'ordering': ('-created_at',),
            },
        ),
    ]
