# Generated by Django 5.2.16 on 2026-08-10 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_complimentary_grant'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(help_text="The number Telegram gives a chat. A person's own id is positive; a group's is negative and starts with -100. A person must press Start on the bot first — Telegram does not let a bot write first.", max_length=32, unique=True, verbose_name='chat id')),
                ('label', models.CharField(help_text='Who or what this is, so the list stays readable a year from now.', max_length=80, verbose_name='label')),
                ('is_active', models.BooleanField(default=True, help_text='Switch off to stop sending without losing the id.', verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'telegram recipient',
                'verbose_name_plural': 'telegram recipients',
                'ordering': ('label',),
            },
        ),
    ]
