# Generated by Django 5.2.16 on 2026-08-17 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_field_labels'),
        ('orders', '0014_telegram_recipient'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer', '-created_at'], name='orders_customer_recent_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', '-created_at'], name='orders_status_recent_idx'),
        ),
    ]
