# Generated by Django 5.2.16 on 2026-08-17 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_order_query_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='esim',
            field=models.ForeignKey(blank=True, help_text='Set on a top-up line: the eSIM the extra data is added to.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='topup_items', to='orders.esim', verbose_name='target eSIM'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='topup_applied_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='top-up applied at'),
        ),
    ]
