# Generated by Django 5.2.16 on 2026-09-09 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_topup_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='esim',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last synced at'),
        ),
    ]
