"""Write down what the tables actually look like.

The schema is owned here and mirrored by hand in the API's SQLAlchemy models,
and a contract test fails CI when the mirror drifts. What neither of those does
is tell a human — or an agent writing a query — what a column is *called*. On
2026-08-22 three separate queries against production failed on guessed names:
`starting_price` (does not exist), `valid_from` (it is `valid_until`), and
`esims_esim` (it is `orders_esim`). Every one of those was a guess that a file
in the repo could have answered.

So: `manage.py dump_schema` writes docs/schema.md from the live tables. It is
generated, committed, and refreshed by CI, so the answer is always one grep away
and always current.
"""

from __future__ import annotations

from pathlib import Path

from django.apps import apps
from django.core.management.base import BaseCommand
from django.db import connection

HEADER = """<!-- Generated by `manage.py dump_schema`. Do not edit by hand. -->

# Schema

Every table below is created by a migration in this repository, which owns the
schema; the API maps a deliberately partial subset of it. See
`docs/adr/0002-one-schema-two-orms.md` for why it is mirrored rather than shared.

Refresh with:

```bash
python manage.py dump_schema
```
"""


class Command(BaseCommand):
    help = "Write docs/schema.md from the live database."

    def add_arguments(self, parser):
        parser.add_argument(
            "--output",
            default="docs/schema.md",
            help="Where to write the file (default: docs/schema.md).",
        )

    def handle(self, *args, **options):
        tables = connection.introspection.table_names()
        models_by_table = {
            model._meta.db_table: model
            for model in apps.get_models()
            if model._meta.db_table in tables
        }

        lines = [HEADER]
        with connection.cursor() as cursor:
            for table in sorted(models_by_table):
                model = models_by_table[table]
                lines.append(f"\n## `{table}`\n")
                doc = (model.__doc__ or "").strip().split("\n")[0]
                if doc and not doc.startswith(model.__name__):
                    lines.append(f"{doc}\n")
                lines.append("| column | type | null | default |")
                lines.append("|---|---|---|---|")
                for column in connection.introspection.get_table_description(cursor, table):
                    null = "yes" if column.null_ok else "no"
                    default = column.default if column.default is not None else ""
                    type_name = connection.introspection.get_field_type(column.type_code, column)
                    lines.append(f"| `{column.name}` | {type_name} | {null} | {default} |")

        path = Path(options["output"])
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text("\n".join(lines) + "\n", encoding="utf-8")
        self.stdout.write(self.style.SUCCESS(f"{path}: {len(models_by_table)} tables"))
